name: Plugin Asset/Readme Update
on:
  push:
    branches:
      - master
    paths:
      - .wordpress-org/*
      - readme.txt
jobs:
  master:
    name: Push to master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: WordPress.org plugin asset/readme update
        uses: bluehost/wp-plugin-readme-assets-updater@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
